-- 코드를 작성해주세요
SELECT
    COUNT(N.FISH_TYPE) AS FISH_COUNT ,FISH_NAME
FROM 
    FISH_INFO AS F
JOIN
    FISH_NAME_INFO AS N
ON 
    F.FISH_TYPE = N.FISH_TYPE
GROUP BY 
    FISH_NAME
ORDER BY 
    FISH_COUNT DESC;